services:
  - type: web
    name: iskon-llm
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn app:app --host 0.0.0.0 --port 8000 --workers 1
    envVars:
      - key: PORT
        value: 8000
